name: a2_caller_wf_tbd
on:
  push:
    branches:
      - dev2
  workflow_dispatch:

jobs:

  debug_secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: print out secret
        env:
          caller_secret: ${{ secrets.ASF_REPO_SECRET }}
        run: |
          echo secrets length is: ${#caller_secret}
          echo secrets length is: ${caller_secret:0:7}

  call_reusable_wf:
    needs: debug_secret
    uses: ardfar68/asf_gh_actions_workflow_repo1/.github/workflows/a_reusable_wf_tbd.yml@dev1
    with:
      exampleInputNew: "This is from caller wf new"
    secrets:
      asf_secret: ${{ secrets.ASF_REPO_SECRET }}

  # ALT_1
  print_result_from_reusable_wf_alt1:
    runs-on: ubuntu-latest
    needs: call_reusable_wf
    steps:
      - name: printing out result from reusable wf
        run: |
          echo sum result from reusable-wf job1:\
          ${{ needs.call_reusable_wf.outputs.sumOutput }}
          echo subtraction result from reusable-wf job2:\
          ${{ needs.call_reusable_wf.outputs.subOutput }}
          echo multiplication result from reusable-wf job2:\
          ${{ needs.call_reusable_wf.outputs.multiOutput }}
          echo division result from reusable-wf job1:\
          ${{ needs.call_reusable_wf.outputs.divOutput }}
        
        # run: |
        #   echo sum is: ${{ needs.call_reusable_wf.outputs.sumOutput }}
        #   echo sub is: ${{ needs.call_reusable_wf.outputs.subOutput }}
        #   echo multi is: ${{ needs.call_reusable_wf.outputs.multiOutput }}
        #   echo div is: ${{ needs.call_reusable_wf.outputs.divOutput }}