name: a2_caller_wf_tbd
on:
  push:
    branches:
      - dev2
  workflow_dispatch:

jobs:
  # debug_secret:
  #   runs-on: ubuntu-latest
  #   env:
  #     my_repo2_secret: ${{ secrets.ASF_REPO_SECRET }}

  #   steps:
  #     - name: print out secret
  #       run: |
  #         echo secrets length is: ${#my_repo2_secret}
  #         echo secrets length is: ${my_repo2_secret:0:7}

  job1_in_caller_wf:
    # needs: debug_secret
    uses: ardfar68/asf_gh_actions_workflow_repo1/.github/workflows/a_reusable_wf_tbd.yml@dev1
    with:
      exampleInputNew: "This is from caller wf new"
    secrets:
      asf_secret: ${{ secrets.ASF_REPO_SECRET }}

 